[build]
  publish = "build"
  command = "npm run build"

# Disable Angular runtime plugin
[dev]
  framework = "#custom"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    disabled = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; object-src 'none'; base-uri 'self';"